#!/usr/bin/env python3

import sys
import re
import operator
import csv

error = {}
per_user = {}

with open ( "./log", "r" ) as f:
	f = f.readlines()

	for line in f:
		print (line)
		if re.search(r"ERROR: ([\w ]*) .*\((\w+)\)", line) is not None:
			err = re.search(r"ERROR: ([\w ]*) .*\((\w+)\)", line) 
			error[err.group(1)] = error.get(err.group(1), 0) + 1
			if err.group(2) not in per_user:
				per_user[err.group(2)] = { 'INFO': 0, 'ERROR': 0 }
			per_user[err.group(2)]['ERROR'] = per_user.get(err.group(2), {}).get('ERROR', 0) + 1

		if re.search(r"INFO: ([\w ]*) .*\((\w+)\)", line) is not None:
			info = re.search(r"INFO: ([\w ]*) .*\((\w+)\)", line)
			if info.group(2) not in per_user:
				per_user[info.group(2)] = { 'INFO': 0, 'ERROR': 0 }
			per_user[info.group(2)]['INFO'] = per_user.get(info.group(2), {}).get('ERROR', 0) + 1

print (error)
print (per_user)

for entry in sorted(error, key=error.get, reverse=True):
	print (entry, error[entry])

for each in sorted(per_user):
	print (each, per_user[each])

#print ( dic3.get('jane', {}).get('info', {}))
